from . import MKRCharacterCustomizer, AngleShift, Aspect1X, Aspect1XBatch, AxBCompare, MKRThemeDebugger
from .image_layout_nodes import MKRImageCombineGrid, MKRImageSplitGrid
from .preview_nodes import MKRBatchCollagePreview
from .heatmap_nodes import x1Heatmap, x1Heightmap
from .material_map_nodes import x1MetalnessMap, x1NormalMap, x1RoughnessMap, x1SpecularMap
from .material_preview_nodes import x1PreviewMaterial
from .tech_art_nodes import x1ChannelBreakout, x1ChannelPack, x1CurvatureFromNormal, x1NormalBlend, x1UVCheckerOverlay
from .tech_art_surface_nodes import x1AOFromHeight, x1IDMapQuantize, x1IDMaskExtract, x1NormalTweak, x1SlopeMaskFromNormal
from .texture_tool_nodes import x1TextureDelight, x1TextureEdgePad, x1TextureOffset, x1TextureSeamless, x1TextureTilePreview
from .social_nodes import (
    MKRshiftSocialPackAssets,
    MKRshiftSocialPackBuilder,
    MKRshiftSocialPackCatalog,
    MKRshiftSocialPromptAtIndex,
)
from .gcode_analysis_nodes import MKRGCodePlanAnalyzer
from .gcode_input_nodes import MKRGCodeLoadMeshModel, MKRGCodeOrcaProfileLoader
from .gcode_modify_nodes import MKRGCodeBedMeshCompensate, MKRGCodeCalibrationTower, MKRGCodeConditionalInjector
from .gcode_nodes import MKRGCodeExport, MKRGCodeHeightmapPlate, MKRGCodePrinterProfile, MKRGCodeSpiralVase
from .gcode_preview_nodes import MKRGCodePreview
from .gcode_slicer_nodes import MKRGCodeExternalSlicer
from .studio_nodes import (
    MKRStudioCompareBoard,
    MKRStudioContactSheet,
    MKRStudioDeliveryPlan,
    MKRStudioReviewBurnIn,
    MKRStudioReviewFrame,
    MKRStudioSlate,
)
from .face_performance_nodes import (
    MKRFacePerformanceEvaluate,
    MKRFacePerformanceEyeMotion,
    MKRFacePerformanceLipRefine,
    MKRFacePerformancePoseMerge,
    MKRFacePerformanceRigApplyDeltas,
    MKRFacePerformanceRigBuildNeutral,
)
from .xlut import xLUT, xLUTOutput
from .xcolor import (
    x1ColorBalance,
    x1ColorMatch,
    x1ColorWheels,
    x1Curves,
    x1FalseColor,
    x1GamutMap,
    x1HSLQualifier,
    x1LUTBlend,
    x1LUTStack,
    x1PaletteMap,
)
from .xprocess import (
    x1Bloom,
    x1Bokeh,
    x1Chromatic,
    x1Film,
    x1Focus,
    x1Fractal,
    x1Pixelate,
    x1Stylize,
    x1Tone,
)
from .xconcepts import (
    x1CRTScan,
    x1Depth,
    x1GlowEdges,
    x1LensDistort,
    x1LightLeak,
    x1SelectiveColor,
    x1SplitTone,
    x1WarpDisplace,
)
from .xcine import (
    x1Diffusion,
    x1FilmDamage,
    x1FilmPrint,
    x1GateWeave,
    x1Halation,
    x1HighlightRollOff,
    x1LensBreathing,
    x1SkinToneProtect,
)
from .vfx_finishing_nodes import x1AnamorphicStreaks, x1HeatHaze
from .vfx_optics_nodes import x1LensDirtBloom, x1ShockwaveDistort
from .xphoto import x1HighlightRecovery, x1LocalContrast, x1SharpenPro
from .xshader import xShader
from .xplay import x1AuraFlow, x1Glitch, x1Kaleido
from .mask_nodes import x1MaskGen
from .xresize import AdvResize
from .xutility_photo import x1DenoiseDetail
from .presave_image_nodes import MKRPreSave
from .presave_media_nodes import MKRPresaveAudio, MKRPresaveVideo
from .media_io_nodes import (
    MKRAudioTrimFadeNormalize,
    MKRBeatSyncRetimer,
    MKRLoadVideoMetadata,
    MKRMuxVideoAudio,
    MKRSceneCutDetector,
)
from .media_extra_nodes import (
    MKRAudioConcat,
    MKRAudioMix,
    MKRBeatMarkerGrid,
    MKRConcatVideos,
    MKRSelectSceneRange,
    MKRTrimVideoByTime,
)
from .media_batch_video_nodes import (
    MKRAssembleFramesToVideo,
    MKRExtractVideoFrames,
    MKRFreezeFrame,
    MKRLoadAudioMetadata,
    MKRReverseVideo,
    MKRVideoCrossfade,
    MKRVideoLoopBuilder,
    MKRVideoSelectRangeByFrames,
    MKRVideoSpeedRamp,
    MKRVideoSplitAtTimes,
)
from .media_batch_transform_nodes import (
    MKRAudioGainPan,
    MKRAudioLimiter,
    MKRAudioResampleConvert,
    MKRAudioSilenceTrim,
    MKRAudioTempoPitch,
    MKRVideoPingPong,
    MKRVideoPosterize,
    MKRVideoResizePad,
    MKRVideoRotateFlip,
    MKRVideoTemporalBlend,
)
from .media_batch_watermark_audio_nodes import (
    MKRAudioBitcrush,
    MKRAudioChannelRouter,
    MKRAudioEQ3Band,
    MKRAudioPadTrimDuration,
    MKRAudioStereoWidth,
    MKRAudioWatermark,
    MKRImageWatermark,
    MKRVideoFrameRateConvert,
    MKRVideoGammaContrast,
    MKRVideoWatermark,
)
from .media_batch_analysis_nodes import (
    MKRAudioClippingDetector,
    MKRBlackFrameDetector,
    MKREDLExport,
    MKREDLImport,
    MKRExportPreset,
    MKRFreezeFrameDetector,
    MKRLoudnessMeter,
    MKRProjectManifest,
    MKRProxyTranscode,
    MKRQualityReport,
)
from .media_batch_cinematic_nodes import (
    MKRAutoReframeSubject,
    MKRDepthFog,
    MKRFilmGatePack,
    MKRLensFX,
    MKRLightWrapComposite,
    MKRMatchCutByMotion,
    MKRMotionBlurVector,
    MKROpticalFlowInterpolate,
    MKRShotMatchColor,
    MKRTimeRemapCurve,
)
from .media_batch_audio_delivery_nodes import (
    MKRChapterMarkerGenerator,
    MKRCompressorGate,
    MKRDeEsser,
    MKRInvisibleAudioWatermark,
    MKRInvisibleImageWatermark,
    MKRLowerThirdTemplate,
    MKRNoiseReductionSpectral,
    MKRSidechainDucker,
    MKRStemSplitter,
    MKRSubtitleBurnIn,
)

NODE_CLASS_MAPPINGS = {
    "MKRCharacterCustomizer": MKRCharacterCustomizer,
    "AngleShift": AngleShift,
    "Aspect1X": Aspect1X,
    "Aspect1XBatch": Aspect1XBatch,
    "AxBCompare": AxBCompare,
    "MKRThemeDebugger": MKRThemeDebugger,
    "MKRImageSplitGrid": MKRImageSplitGrid,
    "MKRImageCombineGrid": MKRImageCombineGrid,
    "MKRGCodePrinterProfile": MKRGCodePrinterProfile,
    "MKRGCodeOrcaProfileLoader": MKRGCodeOrcaProfileLoader,
    "MKRGCodeLoadMeshModel": MKRGCodeLoadMeshModel,
    "MKRGCodeHeightmapPlate": MKRGCodeHeightmapPlate,
    "MKRGCodeSpiralVase": MKRGCodeSpiralVase,
    "MKRGCodePlanAnalyzer": MKRGCodePlanAnalyzer,
    "MKRGCodeBedMeshCompensate": MKRGCodeBedMeshCompensate,
    "MKRGCodeCalibrationTower": MKRGCodeCalibrationTower,
    "MKRGCodeConditionalInjector": MKRGCodeConditionalInjector,
    "MKRGCodePreview": MKRGCodePreview,
    "MKRGCodeExternalSlicer": MKRGCodeExternalSlicer,
    "MKRGCodeExport": MKRGCodeExport,
    "MKRStudioSlate": MKRStudioSlate,
    "MKRStudioReviewFrame": MKRStudioReviewFrame,
    "MKRStudioContactSheet": MKRStudioContactSheet,
    "MKRStudioDeliveryPlan": MKRStudioDeliveryPlan,
    "MKRStudioReviewBurnIn": MKRStudioReviewBurnIn,
    "MKRStudioCompareBoard": MKRStudioCompareBoard,
    "MKRBatchCollagePreview": MKRBatchCollagePreview,
    "x1Heatmap": x1Heatmap,
    "x1Heightmap": x1Heightmap,
    "x1RoughnessMap": x1RoughnessMap,
    "x1SpecularMap": x1SpecularMap,
    "x1MetalnessMap": x1MetalnessMap,
    "x1NormalMap": x1NormalMap,
    "x1PreviewMaterial": x1PreviewMaterial,
    "x1ChannelPack": x1ChannelPack,
    "x1ChannelBreakout": x1ChannelBreakout,
    "x1NormalBlend": x1NormalBlend,
    "x1CurvatureFromNormal": x1CurvatureFromNormal,
    "x1UVCheckerOverlay": x1UVCheckerOverlay,
    "x1SlopeMaskFromNormal": x1SlopeMaskFromNormal,
    "x1AOFromHeight": x1AOFromHeight,
    "x1IDMapQuantize": x1IDMapQuantize,
    "x1IDMaskExtract": x1IDMaskExtract,
    "x1NormalTweak": x1NormalTweak,
    "x1TextureOffset": x1TextureOffset,
    "x1TextureSeamless": x1TextureSeamless,
    "x1TextureTilePreview": x1TextureTilePreview,
    "x1TextureEdgePad": x1TextureEdgePad,
    "x1TextureDelight": x1TextureDelight,
    "MKRshiftSocialPackBuilder": MKRshiftSocialPackBuilder,
    "MKRshiftSocialPackAssets": MKRshiftSocialPackAssets,
    "MKRshiftSocialPromptAtIndex": MKRshiftSocialPromptAtIndex,
    "MKRshiftSocialPackCatalog": MKRshiftSocialPackCatalog,
    "MKRFacePerformanceEyeMotion": MKRFacePerformanceEyeMotion,
    "MKRFacePerformanceLipRefine": MKRFacePerformanceLipRefine,
    "MKRFacePerformanceRigBuildNeutral": MKRFacePerformanceRigBuildNeutral,
    "MKRFacePerformanceRigApplyDeltas": MKRFacePerformanceRigApplyDeltas,
    "MKRFacePerformancePoseMerge": MKRFacePerformancePoseMerge,
    "MKRFacePerformanceEvaluate": MKRFacePerformanceEvaluate,
    "xLUT": xLUT,
    "xLUTOutput": xLUTOutput,
    "x1LUTBlend": x1LUTBlend,
    "x1LUTStack": x1LUTStack,
    "x1ColorWheels": x1ColorWheels,
    "x1Curves": x1Curves,
    "x1ColorBalance": x1ColorBalance,
    "x1HSLQualifier": x1HSLQualifier,
    "x1PaletteMap": x1PaletteMap,
    "x1ColorMatch": x1ColorMatch,
    "x1GamutMap": x1GamutMap,
    "x1FalseColor": x1FalseColor,
    "x1Tone": x1Tone,
    "x1Stylize": x1Stylize,
    "x1Pixelate": x1Pixelate,
    "x1Film": x1Film,
    "x1Fractal": x1Fractal,
    "x1Bloom": x1Bloom,
    "x1Bokeh": x1Bokeh,
    "x1Chromatic": x1Chromatic,
    "x1Focus": x1Focus,
    "x1LightLeak": x1LightLeak,
    "x1SplitTone": x1SplitTone,
    "x1SelectiveColor": x1SelectiveColor,
    "x1LensDistort": x1LensDistort,
    "x1CRTScan": x1CRTScan,
    "x1WarpDisplace": x1WarpDisplace,
    "x1GlowEdges": x1GlowEdges,
    "x1Depth": x1Depth,
    "x1Halation": x1Halation,
    "x1FilmPrint": x1FilmPrint,
    "x1HighlightRollOff": x1HighlightRollOff,
    "x1SkinToneProtect": x1SkinToneProtect,
    "x1Diffusion": x1Diffusion,
    "x1GateWeave": x1GateWeave,
    "x1FilmDamage": x1FilmDamage,
    "x1LensBreathing": x1LensBreathing,
    "x1AnamorphicStreaks": x1AnamorphicStreaks,
    "x1HeatHaze": x1HeatHaze,
    "x1LensDirtBloom": x1LensDirtBloom,
    "x1ShockwaveDistort": x1ShockwaveDistort,
    "x1HighlightRecovery": x1HighlightRecovery,
    "x1LocalContrast": x1LocalContrast,
    "x1SharpenPro": x1SharpenPro,
    "xShader": xShader,
    "x1MaskGen": x1MaskGen,
    "x1DenoiseDetail": x1DenoiseDetail,
    "AdvResize": AdvResize,
    "x1Kaleido": x1Kaleido,
    "x1Glitch": x1Glitch,
    "x1AuraFlow": x1AuraFlow,
    "MKRPreSave": MKRPreSave,
    "MKRPresaveVideo": MKRPresaveVideo,
    "MKRPresaveAudio": MKRPresaveAudio,
    "MKRLoadVideoMetadata": MKRLoadVideoMetadata,
    "MKRMuxVideoAudio": MKRMuxVideoAudio,
    "MKRAudioTrimFadeNormalize": MKRAudioTrimFadeNormalize,
    "MKRSceneCutDetector": MKRSceneCutDetector,
    "MKRBeatSyncRetimer": MKRBeatSyncRetimer,
    "MKRTrimVideoByTime": MKRTrimVideoByTime,
    "MKRConcatVideos": MKRConcatVideos,
    "MKRSelectSceneRange": MKRSelectSceneRange,
    "MKRAudioMix": MKRAudioMix,
    "MKRAudioConcat": MKRAudioConcat,
    "MKRBeatMarkerGrid": MKRBeatMarkerGrid,
    "MKRLoadAudioMetadata": MKRLoadAudioMetadata,
    "MKRExtractVideoFrames": MKRExtractVideoFrames,
    "MKRAssembleFramesToVideo": MKRAssembleFramesToVideo,
    "MKRVideoSplitAtTimes": MKRVideoSplitAtTimes,
    "MKRVideoSelectRangeByFrames": MKRVideoSelectRangeByFrames,
    "MKRReverseVideo": MKRReverseVideo,
    "MKRFreezeFrame": MKRFreezeFrame,
    "MKRVideoLoopBuilder": MKRVideoLoopBuilder,
    "MKRVideoSpeedRamp": MKRVideoSpeedRamp,
    "MKRVideoCrossfade": MKRVideoCrossfade,
    "MKRVideoRotateFlip": MKRVideoRotateFlip,
    "MKRVideoResizePad": MKRVideoResizePad,
    "MKRVideoPingPong": MKRVideoPingPong,
    "MKRVideoTemporalBlend": MKRVideoTemporalBlend,
    "MKRVideoPosterize": MKRVideoPosterize,
    "MKRAudioResampleConvert": MKRAudioResampleConvert,
    "MKRAudioSilenceTrim": MKRAudioSilenceTrim,
    "MKRAudioGainPan": MKRAudioGainPan,
    "MKRAudioLimiter": MKRAudioLimiter,
    "MKRAudioTempoPitch": MKRAudioTempoPitch,
    "MKRImageWatermark": MKRImageWatermark,
    "MKRAudioWatermark": MKRAudioWatermark,
    "MKRVideoWatermark": MKRVideoWatermark,
    "MKRVideoFrameRateConvert": MKRVideoFrameRateConvert,
    "MKRVideoGammaContrast": MKRVideoGammaContrast,
    "MKRAudioEQ3Band": MKRAudioEQ3Band,
    "MKRAudioStereoWidth": MKRAudioStereoWidth,
    "MKRAudioPadTrimDuration": MKRAudioPadTrimDuration,
    "MKRAudioChannelRouter": MKRAudioChannelRouter,
    "MKRAudioBitcrush": MKRAudioBitcrush,
    "MKRQualityReport": MKRQualityReport,
    "MKRBlackFrameDetector": MKRBlackFrameDetector,
    "MKRFreezeFrameDetector": MKRFreezeFrameDetector,
    "MKRAudioClippingDetector": MKRAudioClippingDetector,
    "MKRLoudnessMeter": MKRLoudnessMeter,
    "MKRProxyTranscode": MKRProxyTranscode,
    "MKRExportPreset": MKRExportPreset,
    "MKRProjectManifest": MKRProjectManifest,
    "MKREDLImport": MKREDLImport,
    "MKREDLExport": MKREDLExport,
    "MKROpticalFlowInterpolate": MKROpticalFlowInterpolate,
    "MKRTimeRemapCurve": MKRTimeRemapCurve,
    "MKRAutoReframeSubject": MKRAutoReframeSubject,
    "MKRMatchCutByMotion": MKRMatchCutByMotion,
    "MKRShotMatchColor": MKRShotMatchColor,
    "MKRFilmGatePack": MKRFilmGatePack,
    "MKRLightWrapComposite": MKRLightWrapComposite,
    "MKRMotionBlurVector": MKRMotionBlurVector,
    "MKRLensFX": MKRLensFX,
    "MKRDepthFog": MKRDepthFog,
    "MKRCompressorGate": MKRCompressorGate,
    "MKRDeEsser": MKRDeEsser,
    "MKRNoiseReductionSpectral": MKRNoiseReductionSpectral,
    "MKRSidechainDucker": MKRSidechainDucker,
    "MKRStemSplitter": MKRStemSplitter,
    "MKRInvisibleImageWatermark": MKRInvisibleImageWatermark,
    "MKRInvisibleAudioWatermark": MKRInvisibleAudioWatermark,
    "MKRChapterMarkerGenerator": MKRChapterMarkerGenerator,
    "MKRSubtitleBurnIn": MKRSubtitleBurnIn,
    "MKRLowerThirdTemplate": MKRLowerThirdTemplate,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "MKRCharacterCustomizer": "Character Direction Studio • MKRShift Nodes",
    "AngleShift": "AngleShift Director • MKRShift Nodes",
    "Aspect1X": "Aspect 1:X • MKRShift Nodes",
    "Aspect1XBatch": "Aspect 1xBatch • MKRShift Nodes",
    "AxBCompare": "AxB Compare • MKRShift Nodes",
    "MKRThemeDebugger": "Theme Debugger • MKRShift Nodes",
    "MKRImageSplitGrid": "Image Split Grid • MKRShift Nodes",
    "MKRImageCombineGrid": "Image Combine Grid • MKRShift Nodes",
    "MKRGCodePrinterProfile": "G-code Printer Profile • MKRShift Nodes",
    "MKRGCodeOrcaProfileLoader": "G-code Orca Profile Loader • MKRShift Nodes",
    "MKRGCodeLoadMeshModel": "G-code Load Mesh Model • MKRShift Nodes",
    "MKRGCodeHeightmapPlate": "G-code Heightmap Plate • MKRShift Nodes",
    "MKRGCodeSpiralVase": "G-code Spiral Vase • MKRShift Nodes",
    "MKRGCodePlanAnalyzer": "G-code Plan Analyzer • MKRShift Nodes",
    "MKRGCodeBedMeshCompensate": "G-code Bed Mesh Compensate • MKRShift Nodes",
    "MKRGCodeCalibrationTower": "G-code Calibration Tower • MKRShift Nodes",
    "MKRGCodeConditionalInjector": "G-code Conditional Injector • MKRShift Nodes",
    "MKRGCodePreview": "G-code Preview • MKRShift Nodes",
    "MKRGCodeExternalSlicer": "G-code External Slicer • MKRShift Nodes",
    "MKRGCodeExport": "G-code Export • MKRShift Nodes",
    "MKRStudioSlate": "Studio Slate • MKRShift Nodes",
    "MKRStudioReviewFrame": "Studio Review Frame • MKRShift Nodes",
    "MKRStudioContactSheet": "Studio Contact Sheet • MKRShift Nodes",
    "MKRStudioDeliveryPlan": "Studio Delivery Plan • MKRShift Nodes",
    "MKRStudioReviewBurnIn": "Studio Review Burn-In • MKRShift Nodes",
    "MKRStudioCompareBoard": "Studio Compare Board • MKRShift Nodes",
    "MKRBatchCollagePreview": "XY:PRE • MKRShift Nodes",
    "x1Heatmap": "Heatmap • MKRShift Nodes",
    "x1Heightmap": "Heightmap • MKRShift Nodes",
    "x1RoughnessMap": "Roughness Map • MKRShift Nodes",
    "x1SpecularMap": "Specular Map • MKRShift Nodes",
    "x1MetalnessMap": "Metalness Map • MKRShift Nodes",
    "x1NormalMap": "Normal Map • MKRShift Nodes",
    "x1PreviewMaterial": "Preview Material • MKRShift Nodes",
    "x1ChannelPack": "Channel Pack • MKRShift Nodes",
    "x1ChannelBreakout": "Channel Breakout • MKRShift Nodes",
    "x1NormalBlend": "Normal Blend • MKRShift Nodes",
    "x1CurvatureFromNormal": "Curvature From Normal • MKRShift Nodes",
    "x1UVCheckerOverlay": "UV Checker Overlay • MKRShift Nodes",
    "x1SlopeMaskFromNormal": "Slope Mask From Normal • MKRShift Nodes",
    "x1AOFromHeight": "AO From Height • MKRShift Nodes",
    "x1IDMapQuantize": "ID Map Quantize • MKRShift Nodes",
    "x1IDMaskExtract": "ID Mask Extract • MKRShift Nodes",
    "x1NormalTweak": "Normal Tweak • MKRShift Nodes",
    "x1TextureOffset": "Texture Offset • MKRShift Nodes",
    "x1TextureSeamless": "Texture Seamless • MKRShift Nodes",
    "x1TextureTilePreview": "Texture Tile Preview • MKRShift Nodes",
    "x1TextureEdgePad": "Texture Edge Pad • MKRShift Nodes",
    "x1TextureDelight": "Texture Delight • MKRShift Nodes",
    "MKRshiftSocialPackBuilder": "Social Pack Builder • MKRShift Nodes",
    "MKRshiftSocialPackAssets": "Social Assets Extract • MKRShift Nodes",
    "MKRshiftSocialPromptAtIndex": "Prompt At Index • MKRShift Nodes",
    "MKRshiftSocialPackCatalog": "Pack Catalog • MKRShift Nodes",
    "MKRFacePerformanceEyeMotion": "Face Performance Eye Motion • MKRShift Nodes",
    "MKRFacePerformanceLipRefine": "Face Performance Lip Refine • MKRShift Nodes",
    "MKRFacePerformanceRigBuildNeutral": "Face Performance Rig Build Neutral • MKRShift Nodes",
    "MKRFacePerformanceRigApplyDeltas": "Face Performance Rig Apply Deltas • MKRShift Nodes",
    "MKRFacePerformancePoseMerge": "Face Performance Pose Merge • MKRShift Nodes",
    "MKRFacePerformanceEvaluate": "Face Performance Evaluate Clip • MKRShift Nodes",
    "xLUT": "xLUT • MKRShift Nodes",
    "xLUTOutput": "xLUT Output • MKRShift Nodes",
    "x1LUTBlend": "LUT Blend • MKRShift Nodes",
    "x1LUTStack": "LUT Stack • MKRShift Nodes",
    "x1ColorWheels": "Color Wheels • MKRShift Nodes",
    "x1Curves": "Curves • MKRShift Nodes",
    "x1ColorBalance": "Color Balance • MKRShift Nodes",
    "x1HSLQualifier": "HSL Qualifier • MKRShift Nodes",
    "x1PaletteMap": "Palette Map • MKRShift Nodes",
    "x1ColorMatch": "Color Match • MKRShift Nodes",
    "x1GamutMap": "Gamut Map • MKRShift Nodes",
    "x1FalseColor": "False Color • MKRShift Nodes",
    "x1Tone": "Tone • MKRShift Nodes",
    "x1Stylize": "Stylize • MKRShift Nodes",
    "x1Pixelate": "Pixelate • MKRShift Nodes",
    "x1Film": "Film Grain • MKRShift Nodes",
    "x1Fractal": "Fractal Texture • MKRShift Nodes",
    "x1Bloom": "Bloom • MKRShift Nodes",
    "x1Bokeh": "Bokeh • MKRShift Nodes",
    "x1Chromatic": "Chromatic Shift • MKRShift Nodes",
    "x1Focus": "Focus • MKRShift Nodes",
    "x1LightLeak": "Light Leak • MKRShift Nodes",
    "x1SplitTone": "Split Tone • MKRShift Nodes",
    "x1SelectiveColor": "Selective Color • MKRShift Nodes",
    "x1LensDistort": "Lens Distort • MKRShift Nodes",
    "x1CRTScan": "CRT Scan • MKRShift Nodes",
    "x1WarpDisplace": "Warp Displace • MKRShift Nodes",
    "x1GlowEdges": "Glow Edges • MKRShift Nodes",
    "x1Depth": "Depth FX • MKRShift Nodes",
    "x1Halation": "Halation • MKRShift Nodes",
    "x1FilmPrint": "Film Print • MKRShift Nodes",
    "x1HighlightRollOff": "Highlight Roll-Off • MKRShift Nodes",
    "x1SkinToneProtect": "Skin Tone Protect • MKRShift Nodes",
    "x1Diffusion": "Diffusion • MKRShift Nodes",
    "x1GateWeave": "Gate Weave • MKRShift Nodes",
    "x1FilmDamage": "Film Damage • MKRShift Nodes",
    "x1LensBreathing": "Lens Breathing • MKRShift Nodes",
    "x1AnamorphicStreaks": "Anamorphic Streaks • MKRShift Nodes",
    "x1HeatHaze": "Heat Haze • MKRShift Nodes",
    "x1LensDirtBloom": "Lens Dirt Bloom • MKRShift Nodes",
    "x1ShockwaveDistort": "Shockwave Distort • MKRShift Nodes",
    "x1HighlightRecovery": "Highlight Recovery • MKRShift Nodes",
    "x1LocalContrast": "Local Contrast • MKRShift Nodes",
    "x1SharpenPro": "Sharpen Pro • MKRShift Nodes",
    "xShader": "xShader • MKRShift Nodes",
    "x1MaskGen": "Mask Gen • MKRShift Nodes",
    "x1DenoiseDetail": "Denoise + Detail • MKRShift Nodes",
    "AdvResize": "AdvResize • MKRShift Nodes",
    "x1Kaleido": "Kaleido • MKRShift Nodes",
    "x1Glitch": "Glitch • MKRShift Nodes",
    "x1AuraFlow": "Aura Flow • MKRShift Nodes",
    "MKRPreSave": "Presave Image • MKRShift Nodes",
    "MKRPresaveVideo": "Presave Video • MKRShift Nodes",
    "MKRPresaveAudio": "Presave Audio • MKRShift Nodes",
    "MKRLoadVideoMetadata": "Load Video + Metadata • MKRShift Nodes",
    "MKRMuxVideoAudio": "Mux Video + Audio • MKRShift Nodes",
    "MKRAudioTrimFadeNormalize": "Audio Trim/Fade/Normalize • MKRShift Nodes",
    "MKRSceneCutDetector": "Scene Cut Detector • MKRShift Nodes",
    "MKRBeatSyncRetimer": "Beat Sync Retimer • MKRShift Nodes",
    "MKRTrimVideoByTime": "Trim Video By Time • MKRShift Nodes",
    "MKRConcatVideos": "Concat Videos • MKRShift Nodes",
    "MKRSelectSceneRange": "Select Scene Range • MKRShift Nodes",
    "MKRAudioMix": "Audio Mix • MKRShift Nodes",
    "MKRAudioConcat": "Audio Concat • MKRShift Nodes",
    "MKRBeatMarkerGrid": "Beat Marker Grid • MKRShift Nodes",
    "MKRLoadAudioMetadata": "Load Audio Metadata • MKRShift Nodes",
    "MKRExtractVideoFrames": "Extract Video Frames • MKRShift Nodes",
    "MKRAssembleFramesToVideo": "Assemble Frames To Video • MKRShift Nodes",
    "MKRVideoSplitAtTimes": "Video Split At Times • MKRShift Nodes",
    "MKRVideoSelectRangeByFrames": "Video Select Range By Frames • MKRShift Nodes",
    "MKRReverseVideo": "Reverse Video • MKRShift Nodes",
    "MKRFreezeFrame": "Freeze Frame • MKRShift Nodes",
    "MKRVideoLoopBuilder": "Video Loop Builder • MKRShift Nodes",
    "MKRVideoSpeedRamp": "Video Speed Ramp • MKRShift Nodes",
    "MKRVideoCrossfade": "Video Crossfade • MKRShift Nodes",
    "MKRVideoRotateFlip": "Video Rotate/Flip • MKRShift Nodes",
    "MKRVideoResizePad": "Video Resize + Pad • MKRShift Nodes",
    "MKRVideoPingPong": "Video PingPong • MKRShift Nodes",
    "MKRVideoTemporalBlend": "Video Temporal Blend • MKRShift Nodes",
    "MKRVideoPosterize": "Video Posterize • MKRShift Nodes",
    "MKRAudioResampleConvert": "Audio Resample + Convert • MKRShift Nodes",
    "MKRAudioSilenceTrim": "Audio Silence Trim • MKRShift Nodes",
    "MKRAudioGainPan": "Audio Gain + Pan • MKRShift Nodes",
    "MKRAudioLimiter": "Audio Limiter • MKRShift Nodes",
    "MKRAudioTempoPitch": "Audio Tempo + Pitch • MKRShift Nodes",
    "MKRImageWatermark": "Image Watermark • MKRShift Nodes",
    "MKRAudioWatermark": "Audio Watermark • MKRShift Nodes",
    "MKRVideoWatermark": "Video Watermark • MKRShift Nodes",
    "MKRVideoFrameRateConvert": "Video Frame Rate Convert • MKRShift Nodes",
    "MKRVideoGammaContrast": "Video Gamma + Contrast • MKRShift Nodes",
    "MKRAudioEQ3Band": "Audio EQ 3-Band • MKRShift Nodes",
    "MKRAudioStereoWidth": "Audio Stereo Width • MKRShift Nodes",
    "MKRAudioPadTrimDuration": "Audio Pad/Trim Duration • MKRShift Nodes",
    "MKRAudioChannelRouter": "Audio Channel Router • MKRShift Nodes",
    "MKRAudioBitcrush": "Audio Bitcrush • MKRShift Nodes",
    "MKRQualityReport": "Quality Report • MKRShift Nodes",
    "MKRBlackFrameDetector": "Black Frame Detector • MKRShift Nodes",
    "MKRFreezeFrameDetector": "Freeze Frame Detector • MKRShift Nodes",
    "MKRAudioClippingDetector": "Audio Clipping Detector • MKRShift Nodes",
    "MKRLoudnessMeter": "Loudness Meter • MKRShift Nodes",
    "MKRProxyTranscode": "Proxy Transcode • MKRShift Nodes",
    "MKRExportPreset": "Export Preset • MKRShift Nodes",
    "MKRProjectManifest": "Project Manifest • MKRShift Nodes",
    "MKREDLImport": "EDL Import • MKRShift Nodes",
    "MKREDLExport": "EDL Export • MKRShift Nodes",
    "MKROpticalFlowInterpolate": "Optical Flow Interpolate • MKRShift Nodes",
    "MKRTimeRemapCurve": "Time Remap Curve • MKRShift Nodes",
    "MKRAutoReframeSubject": "Auto Reframe Subject • MKRShift Nodes",
    "MKRMatchCutByMotion": "Match Cut By Motion • MKRShift Nodes",
    "MKRShotMatchColor": "Shot Match Color • MKRShift Nodes",
    "MKRFilmGatePack": "Film Gate Pack • MKRShift Nodes",
    "MKRLightWrapComposite": "Light Wrap Composite • MKRShift Nodes",
    "MKRMotionBlurVector": "Motion Blur Vector • MKRShift Nodes",
    "MKRLensFX": "Lens FX • MKRShift Nodes",
    "MKRDepthFog": "Depth Fog • MKRShift Nodes",
    "MKRCompressorGate": "Compressor + Gate • MKRShift Nodes",
    "MKRDeEsser": "De-Esser • MKRShift Nodes",
    "MKRNoiseReductionSpectral": "Noise Reduction Spectral • MKRShift Nodes",
    "MKRSidechainDucker": "Sidechain Ducker • MKRShift Nodes",
    "MKRStemSplitter": "Stem Splitter • MKRShift Nodes",
    "MKRInvisibleImageWatermark": "Invisible Image Watermark • MKRShift Nodes",
    "MKRInvisibleAudioWatermark": "Invisible Audio Watermark • MKRShift Nodes",
    "MKRChapterMarkerGenerator": "Chapter Marker Generator • MKRShift Nodes",
    "MKRSubtitleBurnIn": "Subtitle Burn-In • MKRShift Nodes",
    "MKRLowerThirdTemplate": "Lower Third Template • MKRShift Nodes",
}

NODE_DISPLAY_NAME_MAPPINGS = {
    key: value.replace(" • MKRShift Nodes", "")
    for key, value in NODE_DISPLAY_NAME_MAPPINGS.items()
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
